## This module contains functions to create a special version of matrix that has its reverse cached.
## When reverse of a matrix is requested, the cached reverse will be used if it is not NULL. Otherwise,
## the reverse of the matrix is computed calling solve() and cached for future use.
##
## First, you should create a cache matrix object by calling makeCacheMatrix with the matrix.
## Then, you can compute the reverse of the given matrix by calling cacheSolve.
## 
## Example:
##     x <- rbind(c(1, 2), c(3, 4))
##     p <- makeCacheMatrix(x)
##     cacheSolve(p)
##
## If the object is not a matrix, makeCacheMatrix will stop and an error message shows up.

## Create a special version of matrix that caches its reverse
## Parameter 
##     x, a matrix object
## Returns a list of fuction
##     get()  returns the matrix itself
##     set(y) reset the matrix to y, the cached reverse will be reset to NULL
##     getReverse()        returns the cached reverse, which could be NULL.
##     setReverse(reverse) set the reverse cache
## Error handling
##     The function will stop if a non-matrix is passed in

makeCacheMatrix <- function(x) {

    ## private function to validate input parameter is a matrix
	stopIfNotMatrix <- function(candidate) {
        if (!is.matrix(candidate)) {
            stop("A matrix is expected")
        }
	}

	stopIfNotMatrix(x)
	reverseCache <- NULL

    get <- function() x
    set <- function(y) {
    	stopIfNotMatrix(y)
    	x <<- y
    	reverseCache <<- NULL
    }

    getReverse <- function() reverseCache
    setReverse <- function(reverse) {
    	stopIfNotMatrix(reverse)
    	reverseCache <<- reverse
    }

    list(set = set, get = get, setReverse = setReverse, getReverse = getReverse)
}


## Get the reverse of a given matrix
## Parameter
##     x, cache matrix object generated by makeCacheMatrix
## Returns 
##     reverse of the given matrix. 

cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    reverse <- x$getReverse()
    if (is.null(reverse)) {
    	message("Cache the reverse of the matrix")
    	reverse = solve(x$get())
        x$setReverse(reverse)
    } else {
    	message("Use the cached reverse of the matrix")
    }
    reverse
}
